# Generated by Django 4.0.2 on 2022-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
