# Generated by Django 3.2.7 on 2022-02-19 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_account_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='proccessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='drop',
            field=models.BooleanField(default=False),
        ),
    ]
